### ISSUE TITLE
Some 7.0 DLC reward blueprints are not "in the scheme" in wares.xml

### ISSUE THREAD

**Issue by Vectorial1024** [DeadAirRT/deadair_eco#4]
More details cross-reference the VRO mod description:

> Instead, with VRO on a new game or save load all blueprints closed behind completing scenarios will be granted for free. 

This includes, for example:

- Argon L Spire
- Argon XL Spire
- Argon Span 1
- Argon Span 2
- etc etc

At the moment, these still requires Hull Parts. It is manageable now that Hull Parts are solely for ship building, but perhaps this should be addressed.

**Comment by DeadAirRT** [comment]
Fixed in version 1.08. Thank you for the report.
