### ISSUE TITLE
Potential problem: difficult-to-use wharves

### ISSUE THREAD

**Issue by Vectorial1024** [DeadAirRT/deadair_eco#6]
The readme mentions limiting the wanted wharves of Argon, Paranid, and Split to 1.

However, this may cause problems:

Let's say I have enabled the Split DLC. Then, if the ARG Wharf in Argon Prime is destroyed, since they still have a wharf somewhere inside Split space, according to the readme, they will not try to rebuild the Argon Prime wharf. This makes S/M shipbuilding difficult.

I am using the X4 Remergence mod, if that would also be important.

**Comment by DeadAirRT** [comment]
That would be feedback for the RE team. I remove the argon and paranid from split sectors completely.

**Comment by Vectorial1024** [comment]
I will let the RE team know about this, thanks!

**Comment by Rothank** [comment]
Thank you for bringing it to us. Thankfully - a non-issue: DA_RE patch already diffs the Wharf quotas back to 2.

**Comment by Vectorial1024** [comment]
I guess this is a false alarm; therefore, indeed, closing this.
